<%@ page language="java" pageEncoding="UTF-8" contentType="text/html;charset=UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<script type="text/javascript">
basePath='<%=basePath%>';
</script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>IoT</title>
<link type="text/css" rel="stylesheet" href="./lib/bootstrap.min.css">
<link type="text/css" rel="stylesheet" href="./lib/font-awesome.min.css">
<link type="text/css" rel="stylesheet" href="./lib/frame.css">
<link type="text/css" rel="stylesheet" href="./lib/menu.css">
<script type="text/javascript" src="./lib/jquery.js"></script>
<script type="text/javascript" src="./lib/bootstrap.min.js"></script>
<script type="text/javascript" src="./lib/frame.js"></script>
</head>
<body>
	<div id="_TOPDIV">
		<nav id="_D1" class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px !important;" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
					<div class="navbar-brand" style="height: 99%; border-right-style: solid; border-right-color: #1277AB; border-right-width: 1px" >
						<h4 style="text-align:center;font-weight: bolder;color: white">机房门禁系统</h4>
					</div>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div id="_TOPIC" class="collapse navbar-collapse">
					<ul class="nav navbar-nav" >
						<!-- generated by js -->
					</ul>
					<div class="navbar-text navbar-right"><a href="./index.jsp">退出</a>
					</div>
				</div>
			</div>
		</nav>
		<div style="box-sizing:border-box" id="_AIM">
			<div id="_D3" class="btn-group-vertical" >
			</div>
			<div id="_S">
				
			</div>
			<div style="clear: both"></div>
		</div>
	</div>
</body>
